// This is a comprehensive database of cities around the world with their timezones
// Format: { name: "City Name", country: "Country Name", timezone: "Timezone/Name" }

export const CITIES_DATABASE = [
  // Africa
  { name: "Abidjan", country: "Ivory Coast", timezone: "Africa/Abidjan" },
  { name: "Accra", country: "Ghana", timezone: "Africa/Accra" },
  { name: "Addis Ababa", country: "Ethiopia", timezone: "Africa/Addis_Ababa" },
  { name: "Alexandria", country: "Egypt", timezone: "Africa/Cairo" },
  { name: "Algiers", country: "Algeria", timezone: "Africa/Algiers" },
  { name: "Antananarivo", country: "Madagascar", timezone: "Indian/Antananarivo" },
  { name: "Asmara", country: "Eritrea", timezone: "Africa/Asmara" },
  { name: "Bamako", country: "Mali", timezone: "Africa/Bamako" },
  { name: "Bangui", country: "Central African Republic", timezone: "Africa/Bangui" },
  { name: "Banjul", country: "Gambia", timezone: "Africa/Banjul" },
  { name: "Bissau", country: "Guinea-Bissau", timezone: "Africa/Bissau" },
  { name: "Blantyre", country: "Malawi", timezone: "Africa/Blantyre" },
  { name: "Brazzaville", country: "Republic of the Congo", timezone: "Africa/Brazzaville" },
  { name: "Bujumbura", country: "Burundi", timezone: "Africa/Bujumbura" },
  { name: "Cairo", country: "Egypt", timezone: "Africa/Cairo" },
  { name: "Cape Town", country: "South Africa", timezone: "Africa/Johannesburg" },
  { name: "Casablanca", country: "Morocco", timezone: "Africa/Casablanca" },
  { name: "Conakry", country: "Guinea", timezone: "Africa/Conakry" },
  { name: "Dakar", country: "Senegal", timezone: "Africa/Dakar" },
  { name: "Dar es Salaam", country: "Tanzania", timezone: "Africa/Dar_es_Salaam" },
  { name: "Djibouti", country: "Djibouti", timezone: "Africa/Djibouti" },
  { name: "Dodoma", country: "Tanzania", timezone: "Africa/Dar_es_Salaam" },
  { name: "Durban", country: "South Africa", timezone: "Africa/Johannesburg" },
  { name: "Freetown", country: "Sierra Leone", timezone: "Africa/Freetown" },
  { name: "Gaborone", country: "Botswana", timezone: "Africa/Gaborone" },
  { name: "Harare", country: "Zimbabwe", timezone: "Africa/Harare" },
  { name: "Johannesburg", country: "South Africa", timezone: "Africa/Johannesburg" },
  { name: "Kampala", country: "Uganda", timezone: "Africa/Kampala" },
  { name: "Khartoum", country: "Sudan", timezone: "Africa/Khartoum" },
  { name: "Kigali", country: "Rwanda", timezone: "Africa/Kigali" },
  { name: "Kinshasa", country: "Democratic Republic of the Congo", timezone: "Africa/Kinshasa" },
  { name: "Lagos", country: "Nigeria", timezone: "Africa/Lagos" },
  { name: "Libreville", country: "Gabon", timezone: "Africa/Libreville" },
  { name: "Lilongwe", country: "Malawi", timezone: "Africa/Blantyre" },
  { name: "Lome", country: "Togo", timezone: "Africa/Lome" },
  { name: "Luanda", country: "Angola", timezone: "Africa/Luanda" },
  { name: "Lubumbashi", country: "Democratic Republic of the Congo", timezone: "Africa/Lubumbashi" },
  { name: "Lusaka", country: "Zambia", timezone: "Africa/Lusaka" },
  { name: "Malabo", country: "Equatorial Guinea", timezone: "Africa/Malabo" },
  { name: "Maputo", country: "Mozambique", timezone: "Africa/Maputo" },
  { name: "Marrakesh", country: "Morocco", timezone: "Africa/Casablanca" },
  { name: "Maseru", country: "Lesotho", timezone: "Africa/Maseru" },
  { name: "Mbabane", country: "Eswatini", timezone: "Africa/Mbabane" },
  { name: "Mogadishu", country: "Somalia", timezone: "Africa/Mogadishu" },
  { name: "Monrovia", country: "Liberia", timezone: "Africa/Monrovia" },
  { name: "Nairobi", country: "Kenya", timezone: "Africa/Nairobi" },
  { name: "N'Djamena", country: "Chad", timezone: "Africa/Ndjamena" },
  { name: "Niamey", country: "Niger", timezone: "Africa/Niamey" },
  { name: "Nouakchott", country: "Mauritania", timezone: "Africa/Nouakchott" },
  { name: "Ouagadougou", country: "Burkina Faso", timezone: "Africa/Ouagadougou" },
  { name: "Port Louis", country: "Mauritius", timezone: "Indian/Mauritius" },
  { name: "Porto-Novo", country: "Benin", timezone: "Africa/Porto-Novo" },
  { name: "Pretoria", country: "South Africa", timezone: "Africa/Johannesburg" },
  { name: "Rabat", country: "Morocco", timezone: "Africa/Casablanca" },
  { name: "Tripoli", country: "Libya", timezone: "Africa/Tripoli" },
  { name: "Tunis", country: "Tunisia", timezone: "Africa/Tunis" },
  { name: "Windhoek", country: "Namibia", timezone: "Africa/Windhoek" },
  { name: "Yamoussoukro", country: "Ivory Coast", timezone: "Africa/Abidjan" },

  // Americas
  { name: "Anchorage", country: "United States", timezone: "America/Anchorage" },
  { name: "Asunción", country: "Paraguay", timezone: "America/Asuncion" },
  { name: "Atlanta", country: "United States", timezone: "America/New_York" },
  { name: "Austin", country: "United States", timezone: "America/Chicago" },
  { name: "Belize City", country: "Belize", timezone: "America/Belize" },
  { name: "Bogotá", country: "Colombia", timezone: "America/Bogota" },
  { name: "Boston", country: "United States", timezone: "America/New_York" },
  { name: "Brasília", country: "Brazil", timezone: "America/Sao_Paulo" },
  { name: "Buenos Aires", country: "Argentina", timezone: "America/Argentina/Buenos_Aires" },
  { name: "Calgary", country: "Canada", timezone: "America/Edmonton" },
  { name: "Cancún", country: "Mexico", timezone: "America/Cancun" },
  { name: "Caracas", country: "Venezuela", timezone: "America/Caracas" },
  { name: "Charlotte", country: "United States", timezone: "America/New_York" },
  { name: "Chicago", country: "United States", timezone: "America/Chicago" },
  { name: "Cincinnati", country: "United States", timezone: "America/New_York" },
  { name: "Cleveland", country: "United States", timezone: "America/New_York" },
  { name: "Columbus", country: "United States", timezone: "America/New_York" },
  { name: "Dallas", country: "United States", timezone: "America/Chicago" },
  { name: "Denver", country: "United States", timezone: "America/Denver" },
  { name: "Detroit", country: "United States", timezone: "America/Detroit" },
  { name: "Edmonton", country: "Canada", timezone: "America/Edmonton" },
  { name: "Fortaleza", country: "Brazil", timezone: "America/Fortaleza" },
  { name: "Georgetown", country: "Guyana", timezone: "America/Guyana" },
  { name: "Guatemala City", country: "Guatemala", timezone: "America/Guatemala" },
  { name: "Guayaquil", country: "Ecuador", timezone: "America/Guayaquil" },
  { name: "Halifax", country: "Canada", timezone: "America/Halifax" },
  { name: "Havana", country: "Cuba", timezone: "America/Havana" },
  { name: "Houston", country: "United States", timezone: "America/Chicago" },
  { name: "Indianapolis", country: "United States", timezone: "America/Indiana/Indianapolis" },
  { name: "Jacksonville", country: "United States", timezone: "America/New_York" },
  { name: "Kansas City", country: "United States", timezone: "America/Chicago" },
  { name: "Kingston", country: "Jamaica", timezone: "America/Jamaica" },
  { name: "La Paz", country: "Bolivia", timezone: "America/La_Paz" },
  { name: "Las Vegas", country: "United States", timezone: "America/Los_Angeles" },
  { name: "Lima", country: "Peru", timezone: "America/Lima" },
  { name: "Los Angeles", country: "United States", timezone: "America/Los_Angeles" },
  { name: "Louisville", country: "United States", timezone: "America/Kentucky/Louisville" },
  { name: "Managua", country: "Nicaragua", timezone: "America/Managua" },
  { name: "Manaus", country: "Brazil", timezone: "America/Manaus" },
  { name: "Memphis", country: "United States", timezone: "America/Chicago" },
  { name: "Mexico City", country: "Mexico", timezone: "America/Mexico_City" },
  { name: "Miami", country: "United States", timezone: "America/New_York" },
  { name: "Milwaukee", country: "United States", timezone: "America/Chicago" },
  { name: "Minneapolis", country: "United States", timezone: "America/Chicago" },
  { name: "Montevideo", country: "Uruguay", timezone: "America/Montevideo" },
  { name: "Montréal", country: "Canada", timezone: "America/Toronto" },
  { name: "Nashville", country: "United States", timezone: "America/Chicago" },
  { name: "New Orleans", country: "United States", timezone: "America/Chicago" },
  { name: "New York", country: "United States", timezone: "America/New_York" },
  { name: "Oklahoma City", country: "United States", timezone: "America/Chicago" },
  { name: "Orlando", country: "United States", timezone: "America/New_York" },
  { name: "Ottawa", country: "Canada", timezone: "America/Toronto" },
  { name: "Panama City", country: "Panama", timezone: "America/Panama" },
  { name: "Paramaribo", country: "Suriname", timezone: "America/Paramaribo" },
  { name: "Philadelphia", country: "United States", timezone: "America/New_York" },
  { name: "Phoenix", country: "United States", timezone: "America/Phoenix" },
  { name: "Pittsburgh", country: "United States", timezone: "America/New_York" },
  { name: "Port-au-Prince", country: "Haiti", timezone: "America/Port-au-Prince" },
  { name: "Portland", country: "United States", timezone: "America/Los_Angeles" },
  { name: "Porto Alegre", country: "Brazil", timezone: "America/Sao_Paulo" },
  { name: "Quito", country: "Ecuador", timezone: "America/Guayaquil" },
  { name: "Recife", country: "Brazil", timezone: "America/Recife" },
  { name: "Regina", country: "Canada", timezone: "America/Regina" },
  { name: "Rio de Janeiro", country: "Brazil", timezone: "America/Sao_Paulo" },
  { name: "Sacramento", country: "United States", timezone: "America/Los_Angeles" },
  { name: "Salt Lake City", country: "United States", timezone: "America/Denver" },
  { name: "San Antonio", country: "United States", timezone: "America/Chicago" },
  { name: "San Diego", country: "United States", timezone: "America/Los_Angeles" },
  { name: "San Francisco", country: "United States", timezone: "America/Los_Angeles" },
  { name: "San Jose", country: "Costa Rica", timezone: "America/Costa_Rica" },
  { name: "San Juan", country: "Puerto Rico", timezone: "America/Puerto_Rico" },
  { name: "San Salvador", country: "El Salvador", timezone: "America/El_Salvador" },
  { name: "Santiago", country: "Chile", timezone: "America/Santiago" },
  { name: "Santo Domingo", country: "Dominican Republic", timezone: "America/Santo_Domingo" },
  { name: "São Paulo", country: "Brazil", timezone: "America/Sao_Paulo" },
  { name: "Seattle", country: "United States", timezone: "America/Los_Angeles" },
  { name: "St. Louis", country: "United States", timezone: "America/Chicago" },
  { name: "Tegucigalpa", country: "Honduras", timezone: "America/Tegucigalpa" },
  { name: "Toronto", country: "Canada", timezone: "America/Toronto" },
  { name: "Vancouver", country: "Canada", timezone: "America/Vancouver" },
  { name: "Washington DC", country: "United States", timezone: "America/New_York" },
  { name: "Winnipeg", country: "Canada", timezone: "America/Winnipeg" },

  // Asia
  { name: "Abu Dhabi", country: "United Arab Emirates", timezone: "Asia/Dubai" },
  { name: "Ahmedabad", country: "India", timezone: "Asia/Kolkata" },
  { name: "Almaty", country: "Kazakhstan", timezone: "Asia/Almaty" },
  { name: "Amman", country: "Jordan", timezone: "Asia/Amman" },
  { name: "Ankara", country: "Turkey", timezone: "Europe/Istanbul" },
  { name: "Ashgabat", country: "Turkmenistan", timezone: "Asia/Ashgabat" },
  { name: "Astana", country: "Kazakhstan", timezone: "Asia/Almaty" },
  { name: "Baghdad", country: "Iraq", timezone: "Asia/Baghdad" },
  { name: "Baku", country: "Azerbaijan", timezone: "Asia/Baku" },
  { name: "Bandung", country: "Indonesia", timezone: "Asia/Jakarta" },
  { name: "Bangkok", country: "Thailand", timezone: "Asia/Bangkok" },
  { name: "Beirut", country: "Lebanon", timezone: "Asia/Beirut" },
  { name: "Beijing", country: "China", timezone: "Asia/Shanghai" },
  { name: "Bengaluru", country: "India", timezone: "Asia/Kolkata" },
  { name: "Bishkek", country: "Kyrgyzstan", timezone: "Asia/Bishkek" },
  { name: "Busan", country: "South Korea", timezone: "Asia/Seoul" },
  { name: "Cebu", country: "Philippines", timezone: "Asia/Manila" },
  { name: "Changsha", country: "China", timezone: "Asia/Shanghai" },
  { name: "Chengdu", country: "China", timezone: "Asia/Shanghai" },
  { name: "Chennai", country: "India", timezone: "Asia/Kolkata" },
  { name: "Chiang Mai", country: "Thailand", timezone: "Asia/Bangkok" },
  { name: "Chongqing", country: "China", timezone: "Asia/Shanghai" },
  { name: "Colombo", country: "Sri Lanka", timezone: "Asia/Colombo" },
  { name: "Damascus", country: "Syria", timezone: "Asia/Damascus" },
  { name: "Davao", country: "Philippines", timezone: "Asia/Manila" },
  { name: "Dhaka", country: "Bangladesh", timezone: "Asia/Dhaka" },
  { name: "Doha", country: "Qatar", timezone: "Asia/Qatar" },
  { name: "Dubai", country: "United Arab Emirates", timezone: "Asia/Dubai" },
  { name: "Dushanbe", country: "Tajikistan", timezone: "Asia/Dushanbe" },
  { name: "Guangzhou", country: "China", timezone: "Asia/Shanghai" },
  { name: "Hangzhou", country: "China", timezone: "Asia/Shanghai" },
  { name: "Hanoi", country: "Vietnam", timezone: "Asia/Ho_Chi_Minh" },
  { name: "Harbin", country: "China", timezone: "Asia/Shanghai" },
  { name: "Ho Chi Minh City", country: "Vietnam", timezone: "Asia/Ho_Chi_Minh" },
  { name: "Hong Kong", country: "China", timezone: "Asia/Hong_Kong" },
  { name: "Hyderabad", country: "India", timezone: "Asia/Kolkata" },
  { name: "Incheon", country: "South Korea", timezone: "Asia/Seoul" },
  { name: "Islamabad", country: "Pakistan", timezone: "Asia/Karachi" },
  { name: "Istanbul", country: "Turkey", timezone: "Europe/Istanbul" },
  { name: "Jakarta", country: "Indonesia", timezone: "Asia/Jakarta" },
  { name: "Jeddah", country: "Saudi Arabia", timezone: "Asia/Riyadh" },
  { name: "Jerusalem", country: "Israel", timezone: "Asia/Jerusalem" },
  { name: "Kabul", country: "Afghanistan", timezone: "Asia/Kabul" },
  { name: "Karachi", country: "Pakistan", timezone: "Asia/Karachi" },
  { name: "Kathmandu", country: "Nepal", timezone: "Asia/Kathmandu" },
  { name: "Kolkata", country: "India", timezone: "Asia/Kolkata" },
  { name: "Kuala Lumpur", country: "Malaysia", timezone: "Asia/Kuala_Lumpur" },
  { name: "Kuwait City", country: "Kuwait", timezone: "Asia/Kuwait" },
  { name: "Kyoto", country: "Japan", timezone: "Asia/Tokyo" },
  { name: "Lahore", country: "Pakistan", timezone: "Asia/Karachi" },
  { name: "Macau", country: "China", timezone: "Asia/Macau" },
  { name: "Makassar", country: "Indonesia", timezone: "Asia/Makassar" },
  { name: "Manila", country: "Philippines", timezone: "Asia/Manila" },
  { name: "Mashhad", country: "Iran", timezone: "Asia/Tehran" },
  { name: "Medan", country: "Indonesia", timezone: "Asia/Jakarta" },
  { name: "Mumbai", country: "India", timezone: "Asia/Kolkata" },
  { name: "Muscat", country: "Oman", timezone: "Asia/Muscat" },
  { name: "Nagoya", country: "Japan", timezone: "Asia/Tokyo" },
  { name: "Nanjing", country: "China", timezone: "Asia/Shanghai" },
  { name: "New Delhi", country: "India", timezone: "Asia/Kolkata" },
  { name: "Nicosia", country: "Cyprus", timezone: "Asia/Nicosia" },
  { name: "Osaka", country: "Japan", timezone: "Asia/Tokyo" },
  { name: "Phnom Penh", country: "Cambodia", timezone: "Asia/Phnom_Penh" },
  { name: "Phuket", country: "Thailand", timezone: "Asia/Bangkok" },
  { name: "Pune", country: "India", timezone: "Asia/Kolkata" },
  { name: "Pyongyang", country: "North Korea", timezone: "Asia/Pyongyang" },
  { name: "Qingdao", country: "China", timezone: "Asia/Shanghai" },
  { name: "Riyadh", country: "Saudi Arabia", timezone: "Asia/Riyadh" },
  { name: "Sapporo", country: "Japan", timezone: "Asia/Tokyo" },
  { name: "Seoul", country: "South Korea", timezone: "Asia/Seoul" },
  { name: "Shanghai", country: "China", timezone: "Asia/Shanghai" },
  { name: "Shenyang", country: "China", timezone: "Asia/Shanghai" },
  { name: "Shenzhen", country: "China", timezone: "Asia/Shanghai" },
  { name: "Singapore", country: "Singapore", timezone: "Asia/Singapore" },
  { name: "Surabaya", country: "Indonesia", timezone: "Asia/Jakarta" },
  { name: "Surat", country: "India", timezone: "Asia/Kolkata" },
  { name: "Taipei", country: "Taiwan", timezone: "Asia/Taipei" },
  { name: "Tashkent", country: "Uzbekistan", timezone: "Asia/Tashkent" },
  { name: "Tbilisi", country: "Georgia", timezone: "Asia/Tbilisi" },
  { name: "Tehran", country: "Iran", timezone: "Asia/Tehran" },
  { name: "Tel Aviv", country: "Israel", timezone: "Asia/Jerusalem" },
  { name: "Tianjin", country: "China", timezone: "Asia/Shanghai" },
  { name: "Tokyo", country: "Japan", timezone: "Asia/Tokyo" },
  { name: "Ulaanbaatar", country: "Mongolia", timezone: "Asia/Ulaanbaatar" },
  { name: "Urumqi", country: "China", timezone: "Asia/Urumqi" },
  { name: "Vientiane", country: "Laos", timezone: "Asia/Vientiane" },
  { name: "Vladivostok", country: "Russia", timezone: "Asia/Vladivostok" },
  { name: "Wuhan", country: "China", timezone: "Asia/Shanghai" },
  { name: "Xi'an", country: "China", timezone: "Asia/Shanghai" },
  { name: "Yangon", country: "Myanmar", timezone: "Asia/Yangon" },
  { name: "Yekaterinburg", country: "Russia", timezone: "Asia/Yekaterinburg" },
  { name: "Yerevan", country: "Armenia", timezone: "Asia/Yerevan" },
  { name: "Yokohama", country: "Japan", timezone: "Asia/Tokyo" },

  // Europe
  { name: "Amsterdam", country: "Netherlands", timezone: "Europe/Amsterdam" },
  { name: "Andorra la Vella", country: "Andorra", timezone: "Europe/Andorra" },
  { name: "Athens", country: "Greece", timezone: "Europe/Athens" },
  { name: "Barcelona", country: "Spain", timezone: "Europe/Madrid" },
  { name: "Belfast", country: "United Kingdom", timezone: "Europe/London" },
  { name: "Belgrade", country: "Serbia", timezone: "Europe/Belgrade" },
  { name: "Berlin", country: "Germany", timezone: "Europe/Berlin" },
  { name: "Bern", country: "Switzerland", timezone: "Europe/Zurich" },
  { name: "Birmingham", country: "United Kingdom", timezone: "Europe/London" },
  { name: "Bratislava", country: "Slovakia", timezone: "Europe/Bratislava" },
  { name: "Brussels", country: "Belgium", timezone: "Europe/Brussels" },
  { name: "Bucharest", country: "Romania", timezone: "Europe/Bucharest" },
  { name: "Budapest", country: "Hungary", timezone: "Europe/Budapest" },
  { name: "Chisinau", country: "Moldova", timezone: "Europe/Chisinau" },
  { name: "Copenhagen", country: "Denmark", timezone: "Europe/Copenhagen" },
  { name: "Cork", country: "Ireland", timezone: "Europe/Dublin" },
  { name: "Dublin", country: "Ireland", timezone: "Europe/Dublin" },
  { name: "Edinburgh", country: "United Kingdom", timezone: "Europe/London" },
  { name: "Florence", country: "Italy", timezone: "Europe/Rome" },
  { name: "Frankfurt", country: "Germany", timezone: "Europe/Berlin" },
  { name: "Geneva", country: "Switzerland", timezone: "Europe/Zurich" },
  { name: "Glasgow", country: "United Kingdom", timezone: "Europe/London" },
  { name: "Gothenburg", country: "Sweden", timezone: "Europe/Stockholm" },
  { name: "Hamburg", country: "Germany", timezone: "Europe/Berlin" },
  { name: "Helsinki", country: "Finland", timezone: "Europe/Helsinki" },
  { name: "Kyiv", country: "Ukraine", timezone: "Europe/Kiev" },
  { name: "Lisbon", country: "Portugal", timezone: "Europe/Lisbon" },
  { name: "Liverpool", country: "United Kingdom", timezone: "Europe/London" },
  { name: "Ljubljana", country: "Slovenia", timezone: "Europe/Ljubljana" },
  { name: "London", country: "United Kingdom", timezone: "Europe/London" },
  { name: "Luxembourg", country: "Luxembourg", timezone: "Europe/Luxembourg" },
  { name: "Lyon", country: "France", timezone: "Europe/Paris" },
  { name: "Madrid", country: "Spain", timezone: "Europe/Madrid" },
  { name: "Manchester", country: "United Kingdom", timezone: "Europe/London" },
  { name: "Marseille", country: "France", timezone: "Europe/Paris" },
  { name: "Milan", country: "Italy", timezone: "Europe/Rome" },
  { name: "Minsk", country: "Belarus", timezone: "Europe/Minsk" },
  { name: "Monaco", country: "Monaco", timezone: "Europe/Monaco" },
  { name: "Moscow", country: "Russia", timezone: "Europe/Moscow" },
  { name: "Munich", country: "Germany", timezone: "Europe/Berlin" },
  { name: "Naples", country: "Italy", timezone: "Europe/Rome" },
  { name: "Nice", country: "France", timezone: "Europe/Paris" },
  { name: "Nicosia", country: "Cyprus", timezone: "Asia/Nicosia" },
  { name: "Oslo", country: "Norway", timezone: "Europe/Oslo" },
  { name: "Palermo", country: "Italy", timezone: "Europe/Rome" },
  { name: "Paris", country: "France", timezone: "Europe/Paris" },
  { name: "Porto", country: "Portugal", timezone: "Europe/Lisbon" },
  { name: "Prague", country: "Czech Republic", timezone: "Europe/Prague" },
  { name: "Reykjavik", country: "Iceland", timezone: "Atlantic/Reykjavik" },
  { name: "Riga", country: "Latvia", timezone: "Europe/Riga" },
  { name: "Rome", country: "Italy", timezone: "Europe/Rome" },
  { name: "Rotterdam", country: "Netherlands", timezone: "Europe/Amsterdam" },
  { name: "Saint Petersburg", country: "Russia", timezone: "Europe/Moscow" },
  { name: "Sarajevo", country: "Bosnia and Herzegovina", timezone: "Europe/Sarajevo" },
  { name: "Seville", country: "Spain", timezone: "Europe/Madrid" },
  { name: "Skopje", country: "North Macedonia", timezone: "Europe/Skopje" },
  { name: "Sofia", country: "Bulgaria", timezone: "Europe/Sofia" },
  { name: "Stockholm", country: "Sweden", timezone: "Europe/Stockholm" },
  { name: "Tallinn", country: "Estonia", timezone: "Europe/Tallinn" },
  { name: "Tirana", country: "Albania", timezone: "Europe/Tirane" },
  { name: "Turin", country: "Italy", timezone: "Europe/Rome" },
  { name: "Vaduz", country: "Liechtenstein", timezone: "Europe/Vaduz" },
  { name: "Valletta", country: "Malta", timezone: "Europe/Malta" },
  { name: "Vienna", country: "Austria", timezone: "Europe/Vienna" },
  { name: "Vilnius", country: "Lithuania", timezone: "Europe/Vilnius" },
  { name: "Warsaw", country: "Poland", timezone: "Europe/Warsaw" },
  { name: "Zagreb", country: "Croatia", timezone: "Europe/Zagreb" },
  { name: "Zurich", country: "Switzerland", timezone: "Europe/Zurich" },

  // Oceania
  { name: "Adelaide", country: "Australia", timezone: "Australia/Adelaide" },
  { name: "Auckland", country: "New Zealand", timezone: "Pacific/Auckland" },
  { name: "Brisbane", country: "Australia", timezone: "Australia/Brisbane" },
  { name: "Christchurch", country: "New Zealand", timezone: "Pacific/Auckland" },
  { name: "Darwin", country: "Australia", timezone: "Australia/Darwin" },
  { name: "Hobart", country: "Australia", timezone: "Australia/Hobart" },
  { name: "Melbourne", country: "Australia", timezone: "Australia/Melbourne" },
  { name: "Nouméa", country: "New Caledonia", timezone: "Pacific/Noumea" },
  { name: "Perth", country: "Australia", timezone: "Australia/Perth" },
  { name: "Port Moresby", country: "Papua New Guinea", timezone: "Pacific/Port_Moresby" },
  { name: "Suva", country: "Fiji", timezone: "Pacific/Fiji" },
  { name: "Sydney", country: "Australia", timezone: "Australia/Sydney" },
  { name: "Wellington", country: "New Zealand", timezone: "Pacific/Auckland" },

  // Pacific
  { name: "Apia", country: "Samoa", timezone: "Pacific/Apia" },
  { name: "Honolulu", country: "United States", timezone: "Pacific/Honolulu" },
  { name: "Nuku'alofa", country: "Tonga", timezone: "Pacific/Tongatapu" },
  { name: "Pago Pago", country: "American Samoa", timezone: "Pacific/Pago_Pago" },
  { name: "Papeete", country: "French Polynesia", timezone: "Pacific/Tahiti" },
]
